development:
  adapter: mysql2
  encoding: utf8
  database: 
  username: 
  password: 
  host: localhost
  port: 33065

production:
  adapter: mysql2
  encoding: utf8
  database: 
  username: 
  password: 
  host: localhost
  port: 33065
